#This file was originally generated by PyScripter's unitest wizard

import unittest
import __init__

class TestBase(unittest.TestCase):

    def setUp(self): 
        pass

    def tearDown(self): 
        pass

    def test__getitem__(self):
        pass

    def test__setitem__(self):
        pass

    def test__delitem__(self):
        pass

    def test__contains__(self):
        pass

    def testget(self):
        pass

    def test__cmp__(self):
        pass

    def test__del__(self):
        pass

    def test__iter__(self):
        pass

    def test__len__(self):
        pass

    def test__repr__(self):
        pass

    def testclose(self):
        pass

    def testclear(self):
        pass

    def testitems(self):
        pass

    def testiteritems(self):
        pass

    def testiterkeys(self):
        pass

    def testitervalues(self):
        pass

    def testkeys(self):
        pass

    def testpop(self):
        pass

    def testpopitem(self):
        pass

    def testsetdefault(self):
        pass

    def testupdate(self):
        pass

    def testvalues(self):
        pass

    def testkeys(self):
        pass

if __name__ == '__main__':
    unittest.main()
